name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.2

permissions:
  contents: write

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure all tags are fetched
      
    - name: Determine latest tag
      id: determine_latest_tag
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "latest_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: python -m build
      
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v4
      with:
        name: logManager-dist
        path: dist/
        
    outputs:
      latest_tag: ${{ steps.determine_latest_tag.outputs.latest_tag }}

  release-package:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-package
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: logManager-dist
        
    - name: Test artifact download
      run: ls -la
      
    - name: Create and Upload Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.build-package.outputs.latest_tag }}
        name: logManager ${{ needs.build-package.outputs.latest_tag }}
        files: |
          *.tar.gz
          *.whl
        make_latest: true
